### ISSUE TITLE
Feature request: multi-language support 📚 🔡 

### ISSUE THREAD

**Issue by giovannibonetti** [jameslittle230/stork#48]
Hi! Thanks for the great project!

I see the [stemming configuration is _hardcoded_ to English](https://github.com/jameslittle230/stork/blob/8f34e0294e6bc585d55ce872189ce15579539da6/src/config/stemming_config.rs#L17).

Is it in the roadmap to make it configurable for other languages?

**Comment by jameslittle230** [comment]
Hi! Thanks for writing in. 

Stork supports multi-language stemming support today, on either a per-index or per-file basis. You can set the `stemming` option in your configuration file to any of the languages supported by [Snowball Stem](https://snowballstem.org):

```toml
[input]
stemming = “French”
```

You can also change the stemming language on a given file independently:

```toml
[input]
...

[[input.files]]
path = “something”
url = “something else”
title = “my title”
stemming = “French”
```

For more information, check out the [Configuration Reference docs page](https://stork-search.net/docs/config-ref).

Going to close this issue as not a bug, but let me know if you have any more questions (or run into any more issues) and I’m happy to help out! Thanks!

James
